r"""dashboard.py — the review dashboard, rendered from the database.

    python scripts/dashboard.py <review> [--open]

Writes reviews/<id>/<id>-dashboard.html — one self-contained page (no
network, no scripts required) built entirely from reviews/<id>/<id>.sqlite:
the definition of done, what moves the needle, the 55-criterion grid, POUR
and 508 FPC coverage, views × modalities with the latest run of each cell,
findings, the vendor-claim comparison, integrity issues and the state-log
history. Every run, walkthrough and stage file is a relative link, so the
page is the reviewer's map of the review folder.

Regenerated by every `review_db.py sync` (which validate / status /
coverage / log-test / the probe all call), so it is never behind the
files by more than one command. Deterministic — no timestamps; the header
carries the source hash — so a diff on the committed page means the review
changed. Never hand-edit it.

Colour conventions follow the dataviz status palette: every status carries
a glyph and a word as well as a colour, so nothing reads by colour alone.
"""
from __future__ import annotations

import argparse
import html
import pathlib
import re
import sys
import webbrowser

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import review as rv  # noqa: E402
import review_db as db  # noqa: E402

OUTCOME_CLASS = {"Supports": "good", "Partially Supports": "serious", "Does Not Support": "critical",
                 "Not Applicable": "neutral", "Not Evaluated": "empty"}
OUTCOME_GLYPH = {"Supports": "✓", "Partially Supports": "!", "Does Not Support": "✗",
                 "Not Applicable": "–", "Not Evaluated": "·"}
RESULT_CLASS = {"Works": "good", "Works with issues": "warning", "Broken": "critical", "N/A": "neutral",
                "Not set": "pending"}
RESULT_GLYPH = {"Works": "✓", "Works with issues": "!", "Broken": "✗", "N/A": "n", "Not set": "?"}
MOD_ABBR = {"no-vision": "NV", "low-vision": "LV", "no-color": "NC", "no-hearing": "NH",
            "no-speech": "NS", "motor": "MO", "cognition": "CO"}
SEV_CLASS = {"Blocker": "critical", "Major": "serious", "Minor": "warning"}


def e(s) -> str:
    return html.escape("" if s is None else str(s), quote=True)


# --------------------------------------------------------------------------
# data — state_data() plus the detail the console dashboard truncates
# --------------------------------------------------------------------------
def gather(con, review: pathlib.Path) -> dict:
    rid = review.name
    d = db.state_data(con, rid)
    q = lambda sql, **kw: con.execute(sql, {"r": rid, **kw}).fetchall()  # noqa: E731

    evidenced = {sc for (sc,) in q("""SELECT DISTINCT cc.sc FROM check_outcomes ck JOIN check_criteria cc USING (check_id)
                                      WHERE ck.review_id=:r AND ck.outcome IN ('pass','fail','partial','n/a')""")}
    failing = {sc: n for sc, n in q("""SELECT cc.sc, COUNT(*) FROM check_outcomes ck JOIN check_criteria cc USING (check_id)
                                       WHERE ck.review_id=:r AND ck.outcome IN ('fail','partial') GROUP BY cc.sc""")}
    d["criteria"] = [{"sc": sc, "name": n, "level": lv, "principle_no": p, "principle": pn,
                      "outcome": o or "Not Evaluated", "claim": c or "", "findings": tf or "",
                      "url": u or "", "evidenced": sc in evidenced, "failing_checks": failing.get(sc, 0)}
                     for sc, n, lv, p, pn, o, c, tf, u in q("""
        SELECT w.sc, w.name, w.level, w.principle_no, w.principle, o.outcome, o.vendor_claim, o.task_findings,
               w.understanding_url FROM wcag_criteria w
        LEFT JOIN criterion_outcomes o ON o.sc=w.sc AND o.review_id=:r
        WHERE w.in_target=1 ORDER BY w.sort_key""")]

    # matrix with the latest run of each cell
    for m in d["matrix"]:
        m["runs"] = {}
        for mod in rv.REQUIRED_MODALITIES:
            row = q("""SELECT run_id, result, tool,
                       (SELECT COUNT(*) FROM check_outcomes ck WHERE ck.review_id=runs.review_id AND ck.run_id=runs.run_id AND ck.outcome='')
                       FROM runs WHERE review_id=:r AND UPPER(view_id)=UPPER(:v) AND modality=:m ORDER BY run_id DESC LIMIT 1""",
                    v=m["view"], m=mod)
            m["runs"][mod] = ({"run": row[0][0], "result": row[0][1] or "Not set", "tool": row[0][2], "blank": row[0][3]}
                              if row else None)
        m["sweeps"] = [r[0] for r in q("SELECT run_id FROM runs WHERE review_id=:r AND UPPER(view_id)=UPPER(:v) AND LOWER(tool) IN ('axe','wave') ORDER BY run_id", v=m["view"])]

    d["findings_list"] = [{"id": f, "severity": s or "", "section": sec, "view": v or "", "task": t or "",
                           "where": w or "", "withdrawn": bool(wd), "criteria": (c or "").split(","),
                           "runs": sorted(set((r or "").split(",")) - {""})}
                          for f, s, sec, v, t, w, wd, c, r in q("""
        SELECT f.finding_id, f.severity, f.section, f.view_id, f.task_id, f.where_text, f.withdrawn,
               (SELECT group_concat(sc) FROM (SELECT sc FROM finding_criteria fc WHERE fc.review_id=f.review_id AND fc.finding_id=f.finding_id ORDER BY sc)),
               (SELECT group_concat(run_id) FROM (SELECT run_id FROM finding_runs fr WHERE fr.review_id=f.review_id AND fr.finding_id=f.finding_id ORDER BY run_id))
        FROM findings f WHERE f.review_id=:r
        ORDER BY f.withdrawn, CASE WHEN f.severity LIKE 'Blocker%' THEN 0 WHEN f.severity LIKE 'Major%' THEN 1 WHEN f.severity LIKE 'Minor%' THEN 2 ELSE 3 END, f.finding_id""")]

    d["measured_detail"] = [{"sc": sc, "name": n, "check": c, "runs": (runs or "").split(",")}
                            for sc, n, c, runs in q("""
        SELECT cc.sc, w.name, ck.check_id, group_concat(ck.run_id)
        FROM check_outcomes ck JOIN check_criteria cc USING (check_id)
        JOIN criterion_outcomes co ON co.review_id=ck.review_id AND co.sc=cc.sc
        JOIN wcag_criteria w ON w.sc=cc.sc
        WHERE ck.review_id=:r AND ck.outcome IN ('fail','partial') AND co.outcome='Not Evaluated'
        GROUP BY cc.sc, ck.check_id ORDER BY cc.sc, ck.check_id""")]

    d["tasks_detail"] = [{"task": t, "name": n, "verdict": v, "baselines": b or "", "dates": dt or ""}
                         for t, n, v, b, dt in q("SELECT task_id, name, verdict, baselines, dates FROM tasks WHERE review_id=:r ORDER BY task_id")]
    d["integrity_detail"] = db.integrity(con, rid)
    d["vendor_rows"] = [{"sc": sc, "claim": c, "outcome": o} for sc, c, o in q("""
        SELECT sc, vendor_claim, outcome FROM criterion_outcomes WHERE review_id=:r AND outcome<>'Not Evaluated'
        AND vendor_claim<>'' AND vendor_claim NOT LIKE outcome || '%' ORDER BY sc""")]
    d["unanswered_runs"] = [{"run": r, "view": v, "modality": m, "tool": t, "blank": n} for r, v, m, t, n in q("""
        SELECT r.run_id, r.view_id, r.modality, r.tool, COUNT(*) FROM runs r JOIN check_outcomes ck USING (review_id, run_id)
        WHERE r.review_id=:r AND ck.outcome='' GROUP BY r.run_id ORDER BY COUNT(*) DESC, r.run_id""")]

    log = review / "state-log.md"
    d["history"] = []
    if log.exists():
        for ln in log.read_text(encoding="utf-8").splitlines():
            if ln.startswith("| 20"):
                d["history"].append([c.strip() for c in ln.strip().strip("|").split("|")])
    return d


# --------------------------------------------------------------------------
# render
# --------------------------------------------------------------------------
CSS = """
:root{color-scheme:light;--bg:#f6f6f4;--surface:#fcfcfb;--line:#dcdbd6;--ink:#0b0b0b;--ink2:#52514e;--ink3:#7d7c78;
--track:#e8e7e3;--fill:#2a78d6;--good:#0ca30c;--warning:#fab219;--serious:#ec835a;--critical:#d03b3b;--neutral:#9a9994;
--good-bg:#e4f5e4;--warning-bg:#fff3d6;--serious-bg:#fde6dc;--critical-bg:#f9dcdc;--neutral-bg:#ecebe8;--pending-bg:#e6effa;--link:#1d5fb0}
@media (prefers-color-scheme: dark){:root{color-scheme:dark;--bg:#121211;--surface:#1a1a19;--line:#33332f;--ink:#fff;--ink2:#c3c2b7;--ink3:#8f8e87;
--track:#2a2a27;--fill:#3987e5;--good-bg:#173d17;--warning-bg:#4a3a0e;--serious-bg:#4d2a1c;--critical-bg:#4d1f1f;--neutral-bg:#2c2c29;--pending-bg:#1c2c40;--link:#7db3f0}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.45 system-ui,Segoe UI,Roboto,sans-serif;padding:16px}
main{max-width:1440px;margin:0 auto}a{color:var(--link)}h1{font-size:22px;margin:0 0 4px}h2{font-size:15px;margin:0 0 10px;letter-spacing:.02em;text-transform:uppercase;color:var(--ink2)}
h3{font-size:13px;margin:14px 0 6px;color:var(--ink2)}.sub{color:var(--ink2);margin:0 0 14px}.sub code{font-size:12px}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(380px,100%),1fr));gap:16px;align-items:start}
section{background:var(--surface);border:1px solid var(--line);border-radius:8px;padding:14px 16px;min-width:0}
section.wide{grid-column:1/-1}table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;padding:4px 8px;border-bottom:1px solid var(--line);vertical-align:top}
th{color:var(--ink2);font-weight:600;white-space:nowrap}td.num,th.num{text-align:right;font-variant-numeric:tabular-nums}.scroll{overflow-x:auto}
.chips{display:flex;flex-wrap:wrap;gap:6px;margin:6px 0}.chip{display:inline-flex;align-items:center;gap:5px;padding:2px 9px;border-radius:999px;border:1px solid var(--line);background:var(--neutral-bg);font-size:12px;white-space:nowrap}
.chip.good{background:var(--good-bg);border-color:var(--good)}.chip.warning{background:var(--warning-bg);border-color:var(--warning)}
.chip.serious{background:var(--serious-bg);border-color:var(--serious)}.chip.critical{background:var(--critical-bg);border-color:var(--critical)}
.chip.pending{background:var(--pending-bg);border-color:var(--fill)}
.done{display:grid;grid-template-columns:minmax(150px,auto) 1fr auto;gap:4px 12px;align-items:center;font-variant-numeric:tabular-nums}
.done .name{white-space:nowrap}.done .name.ok::before{content:"✓ ";color:var(--good)}.done .name.no::before{content:"✗ ";color:var(--ink3)}
.bar{height:10px;background:var(--track);border-radius:4px;overflow:hidden}.bar i{display:block;height:100%;background:var(--fill);border-radius:4px}
.bar.ok i{background:var(--good)}.done .n{color:var(--ink2);font-size:12px;white-space:nowrap}
.hero{font-size:34px;font-weight:700;line-height:1;margin:2px 0 10px}.hero small{font-size:14px;font-weight:400;color:var(--ink2);margin-left:6px}
.cgrid{display:flex;flex-wrap:wrap;gap:4px;margin:4px 0 10px}.cell{width:46px;height:34px;border-radius:5px;border:1px solid var(--line);display:flex;flex-direction:column;align-items:center;justify-content:center;font-size:11px;line-height:1.1;text-decoration:none;color:var(--ink)}
.cell b{font-size:12px}.cell.good{background:var(--good-bg);border-color:var(--good)}.cell.serious{background:var(--serious-bg);border-color:var(--serious)}
.cell.critical{background:var(--critical-bg);border-color:var(--critical)}.cell.neutral{background:var(--neutral-bg)}.cell.empty{background:transparent;color:var(--ink3);border-style:dashed}
.cell.empty.ev{border-style:solid;border-color:var(--fill);color:var(--ink)}
.legend{display:flex;flex-wrap:wrap;gap:10px;font-size:12px;color:var(--ink2);margin:6px 0}.legend span::before{content:"";display:inline-block;width:11px;height:11px;border-radius:3px;border:1px solid var(--line);margin-right:5px;vertical-align:-1px}
.legend .good::before{background:var(--good-bg);border-color:var(--good)}.legend .serious::before{background:var(--serious-bg);border-color:var(--serious)}
.legend .critical::before{background:var(--critical-bg);border-color:var(--critical)}.legend .neutral::before{background:var(--neutral-bg)}
.legend .warning::before{background:var(--warning-bg);border-color:var(--warning)}.legend .pending::before{background:var(--pending-bg);border-color:var(--fill)}
.legend .empty::before{border-style:dashed}.legend .ev::before{border-color:var(--fill)}
.mx td{padding:3px 5px;text-align:center;white-space:nowrap}.mx td.v{text-align:left;max-width:280px;overflow:hidden;text-overflow:ellipsis}
.mx a{display:inline-block;min-width:44px;padding:2px 4px;border-radius:4px;border:1px solid var(--line);text-decoration:none;color:var(--ink);font-size:11px;line-height:1.2}
.mx a.good{background:var(--good-bg);border-color:var(--good)}.mx a.warning{background:var(--warning-bg);border-color:var(--warning)}
.mx a.critical{background:var(--critical-bg);border-color:var(--critical)}.mx a.neutral{background:var(--neutral-bg)}.mx a.pending{background:var(--pending-bg);border-color:var(--fill)}
.mx span.none{color:var(--ink3)}ul{margin:4px 0 8px 18px;padding:0}li{margin:2px 0}.muted{color:var(--ink3)}.key{font-weight:700;color:var(--serious)}
.needle li{margin:4px 0}.small{font-size:12px}
"""


def chip(text, cls="", glyph="") -> str:
    return f'<span class="chip {cls}">{e(glyph)}{" " if glyph else ""}{e(text)}</span>'


def render(d: dict, review: pathlib.Path) -> str:
    L = []
    sat = sum(1 for r in d["completion"] if r["total"] and r["done"] >= r["total"])
    wt = d["walkthrough_pending"]
    L.append(f"<title>{e(d['product'])} review dashboard</title><style>{CSS}</style><main>")
    L.append(f"<h1>{e(d['product'])} <span class='muted'>· {e(d['review'])}</span></h1>")
    L.append(f"<p class='sub'>decision <b>{e(d['decision'])}</b> · report <b>{e(d['report_status'] or '—')}</b> · "
             f"{d['runs']} runs · {d['findings_live']} live findings ({d['findings_withdrawn']} withdrawn) · "
             f"source <code>{e(d['source_sha'][:12])}</code> · generated by <code>scripts/dashboard.py</code> from "
             f"<code>{e(d['review'])}.sqlite</code> — never hand-edited</p>")
    L.append("<div class='chips'>" + "".join(
        chip(f"{t['task']} {t['verdict']}", {"Pass": "good", "Pass with barriers": "warning", "Fail": "critical"}.get(t["verdict"], ""),
             {"Pass": "✓", "Pass with barriers": "!", "Fail": "✗"}.get(t["verdict"], "·")) for t in d["tasks"]) + "</div>")
    L.append("<div class='grid'>")

    # definition of done
    L.append("<section><h2>Definition of done</h2>")
    L.append(f"<div class='hero'>{sat}<small>of {len(d['completion'])} predicates</small></div><div class='done'>")
    for r in d["completion"]:
        ok = r["total"] and r["done"] >= r["total"]
        pct = 100 * r["done"] / r["total"] if r["total"] else 0
        L.append(f"<span class='name {'ok' if ok else 'no'}' title='{e(r['description'])}'>{e(r['name'])}</span>"
                 f"<span class='bar {'ok' if ok else ''}'><i style='width:{pct:.0f}%'></i></span>"
                 f"<span class='n'>{r['done']}/{r['total']}</span>")
    L.append("</div><p class='small muted'>C12 is the reviewer's act alone. Source: <code>review_db.py completion</code>.</p>")
    L.append("<h3>Coverage — POUR</h3><div class='scroll'><table><tr><th>principle</th><th class='num'>criteria</th><th class='num'>decided</th><th class='num'>evidenced</th><th class='num'>failing</th></tr>")
    for p in d["pour"]:
        L.append(f"<tr><td>{e(p['principle'])}</td><td class='num'>{p['criteria']}</td><td class='num'>{p['decided']}</td><td class='num'>{p['evidenced']}</td><td class='num'>{p['failing']}</td></tr>")
    L.append("</table></div>")
    L.append("<h3>Coverage — 508 FPC</h3><div class='scroll'><table><tr><th>FPC</th><th>modality</th><th class='num'>views with a Result</th><th class='num'>answered</th><th class='num'>blank</th><th class='num'>fails</th></tr>")
    for f in d["fpc"]:
        L.append(f"<tr><td>{e(f['fpc'])}</td><td>{e(f['modality'])}</td><td class='num'>{f['views_resulted']}/{f['views']}</td>"
                 f"<td class='num'>{f['answered']}</td><td class='num'>{f['blank']}</td><td class='num'>{f['fails']}</td></tr>")
    L.append("</table></div>")
    v = d["vendor"]
    L.append(f"<h3>Vendor claim vs verified</h3><div class='chips'>{chip(f'{v['decided']} decided')}"
             f"{chip(f'{v['worse']} worse than claimed', 'critical' if v['worse'] else '')}{chip(f'{v['better']} better', 'good' if v['better'] else '')}{chip(f'{v['same']} as claimed')}</div>")
    if d["vendor_rows"]:
        L.append("<div class='scroll'><table><tr><th>SC</th><th>vendor claim</th><th>verified</th></tr>")
        for r in d["vendor_rows"]:
            L.append(f"<tr><td>{e(r['sc'])}</td><td class='small'>{e(r['claim'][:70])}</td><td>{e(r['outcome'])}</td></tr>")
        L.append("</table></div>")
    L.append("</section>")

    # what moves the needle
    L.append("<section class='needle'><h2>What moves the needle</h2>")
    if wt:
        files = sorted({s["file"] for s in wt})
        L.append(f"<h3>Walkthrough — {len(wt)} of {d['walkthrough_total']} steps pending</h3><ul>")
        for s in wt:
            L.append(f"<li><a href='{e(s['file'])}'>{e(s['step'])}</a>{' <span class=key>KEY</span>' if s['key'] else ''} — {e(s['title'])}</li>")
        L.append("</ul>" + "".join(f"<p class='small muted'>file: <a href='{e(f)}'>{e(f)}</a></p>" for f in files))
    if d["measured_detail"]:
        L.append(f"<h3>05 decisions waiting on a fail / partial check ({len(d['measured_detail'])} criterion×check)</h3><ul>")
        for m in d["measured_detail"]:
            L.append(f"<li><b>{e(m['sc'])}</b> {e(m['name'])} — {e(m['check'])} on " + ", ".join(
                f"<a href='evidence/runs/{e(r)}/run.md'>{e(r)}</a>" for r in m["runs"]) + "</li>")
        L.append("</ul>")
    not_run = [t for t in d["tasks"] if t["verdict"] not in ("Pass", "Pass with barriers", "Fail")]
    if not_run:
        L.append("<h3>Task walks without a verdict</h3><p>" + ", ".join(f"<b>{e(t['task'])}</b> ({e(t['verdict'])})" for t in not_run) + " — <a href='04-task-testing.md'>04-task-testing.md</a> §A</p>")
    if d["unanswered_by_modality"]:
        L.append("<h3>Unanswered check rows by modality</h3><div class='chips'>" + "".join(
            chip(f"{'sweep triage W1–W3' if u['modality'] in ('—', '') else u['modality']} {u['rows']}") for u in d["unanswered_by_modality"]) + "</div>")
    if d["integrity_detail"]:
        L.append("<h3>Integrity (C11)</h3><ul>")
        for i in d["integrity_detail"]:
            items = i["items"]
            L.append(f"<li><b>{e(i['check'])}</b> ({i['count']}) <span class='muted'>— {e(i['description'])}</span><br><span class='small'>"
                     + e("; ".join(str(x) for x in items[:8])) + (f" … +{len(items) - 8}" if len(items) > 8 else "") + "</span></li>")
        L.append("</ul>")
    else:
        L.append("<p>Integrity: clean.</p>")
    L.append("</section>")

    # criteria grid
    L.append("<section class='wide'><h2>WCAG 2.2 AA — 55 criteria (05 outcome)</h2>")
    L.append("<div class='legend'><span class='good'>✓ Supports</span><span class='serious'>! Partially Supports</span>"
             "<span class='critical'>✗ Does Not Support</span><span class='neutral'>– Not Applicable</span>"
             "<span class='empty'>· Not Evaluated</span><span class='empty ev'>· Not Evaluated, but a check is answered</span></div>")
    for pno, pname in sorted(rv.PRINCIPLES.items()):
        cs = [c for c in d["criteria"] if str(c["principle_no"]) == pno]
        L.append(f"<h3>{e(pno)} {e(pname)} <span class='muted'>— {sum(1 for c in cs if c['outcome'] != 'Not Evaluated')}/{len(cs)} decided</span></h3><div class='cgrid'>")
        for c in cs:
            cls = OUTCOME_CLASS.get(c["outcome"], "empty") + (" ev" if c["evidenced"] and c["outcome"] == "Not Evaluated" else "")
            title = f"{c['sc']} {c['name']} ({c['level']}) — {c['outcome']}" + (f"; findings: {c['findings']}" if c["findings"] else "") \
                + (f"; {c['failing_checks']} failing check row(s)" if c["failing_checks"] else "") + ("; check evidence" if c["evidenced"] else "; no answered check")
            L.append(f"<a class='cell {cls}' href='05-results.md' title='{e(title)}'><b>{e(c['sc'])}</b><span>{e(OUTCOME_GLYPH.get(c['outcome'], '·'))} {e(c['level'])}</span></a>")
        L.append("</div>")
    L.append("<p class='small muted'>Hover a cell for the name, outcome, findings and check evidence; click for <a href='05-results.md'>05-results.md</a>.</p></section>")

    # matrix
    L.append("<section class='wide'><h2>Views × modalities — latest run of each cell</h2>")
    L.append("<div class='legend'><span class='good'>✓ Works</span><span class='warning'>! Works with issues</span><span class='critical'>✗ Broken</span>"
             "<span class='neutral'>n N/A</span><span class='pending'>? logged, no Result (blank rows in brackets)</span><span class='empty'>· not run</span></div>")
    L.append("<div class='scroll'><table class='mx'><tr><th>view</th>" + "".join(f"<th title='{e(m)}'>{MOD_ABBR[m]}</th>" for m in rv.REQUIRED_MODALITIES) + "<th>sweep</th></tr>")
    for m in d["matrix"]:
        L.append(f"<tr><td class='v' title='{e(m['name'])}'><b>{e(m['view'])}</b> {e(m['name'])}</td>")
        for mod in rv.REQUIRED_MODALITIES:
            r = m["runs"][mod]
            if not r:
                L.append("<td><span class='none'>·</span></td>")
                continue
            cls = RESULT_CLASS.get(r["result"], "pending")
            blank = f" ({r['blank']})" if r["result"] == "Not set" and r["blank"] else ""
            L.append(f"<td><a class='{cls}' href='evidence/runs/{e(r['run'])}/run.md' title='{e(r['run'])} — {e(r['result'])} — {e(r['tool'])}'>"
                     f"{e(RESULT_GLYPH.get(r['result'], '?'))} {e(r['run'])}{e(blank)}</a></td>")
        L.append("<td>" + (" ".join(f"<a class='neutral' href='evidence/runs/{e(s)}/run.md'>{e(s)}</a>" for s in m["sweeps"]) or "<span class='none'>·</span>") + "</td></tr>")
    L.append("</table></div></section>")

    # findings
    s = d["severity"]
    L.append(f"<section class='wide'><h2>Findings</h2><div class='chips'>{chip(f'Blocker {s['Blocker']}', 'critical', '✗')}"
             f"{chip(f'Major {s['Major']}', 'serious', '!')}{chip(f'Minor {s['Minor']}', 'warning', '!')}"
             + (chip(f"unrated {s['unrated']}") if s["unrated"] else "") + chip(f"withdrawn {d['findings_withdrawn']}") + "</div>")
    L.append("<div class='scroll'><table><tr><th>ID</th><th>severity</th><th>where</th><th>criteria</th><th>runs</th></tr>")
    for f in d["findings_list"]:
        sev = re.search(r"Blocker|Major|Minor", f["severity"] or "")
        cls = SEV_CLASS.get(sev.group(0), "") if sev else ""
        style = " style='opacity:.55'" if f["withdrawn"] else ""
        L.append(f"<tr{style}><td><a href='04-task-testing.md'>{e(f['id'])}</a></td><td>{chip(f['severity'][:60] or '—', cls) if not f['withdrawn'] else chip('withdrawn')}</td>"
                 f"<td class='small'>{e(f['where'][:140])}</td><td>{e(', '.join(c for c in f['criteria'] if c))}</td>"
                 f"<td>{' '.join(f'<a href=\"evidence/runs/{e(r)}/run.md\">{e(r)}</a>' for r in f['runs'])}</td></tr>")
    L.append("</table></div></section>")

    # history
    L.append("<section class='wide'><h2>History — state-log.md</h2>")
    if d["history"]:
        cols = ["date", "done", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11", "C12", "runs", "findings", "integrity"]
        L.append("<div class='scroll'><table><tr>" + "".join(f"<th>{c}</th>" for c in cols) + "</tr>")
        for row in d["history"]:
            L.append("<tr>" + "".join(f"<td class='small'>{e(c)}</td>" for c in row) + "</tr>")
        L.append("</table></div>")
    else:
        L.append("<p class='muted'>no rows yet — <code>review_db.py state --log</code></p>")
    L.append("<p class='small muted'>Runs with blank rows: " + ", ".join(
        f"<a href='evidence/runs/{e(u['run'])}/run.md' title='{e(u['view'])} × {e(u['modality'])} ({e(u['tool'])})'>{e(u['run'])}</a> ({u['blank']})"
        for u in d["unanswered_runs"][:30]) + (f" … +{len(d['unanswered_runs']) - 30}" if len(d["unanswered_runs"]) > 30 else "") + "</p>")
    L.append("<p class='small muted'>Stage files: " + " · ".join(f"<a href='{e(s)}'>{e(s)}</a>" for s in rv.STAGES) + "</p></section>")
    L.append("</div></main>")
    return "<!doctype html><html lang='en'><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>" + "\n".join(L) + "\n"


def out_path(review: pathlib.Path) -> pathlib.Path:
    return review / f"{review.name}-dashboard.html"


def write(review: pathlib.Path, con=None) -> tuple[pathlib.Path, bool]:
    """Render the dashboard from the review's database. Returns (path, changed).
    Byte-stable: an unchanged page is not rewritten."""
    own = con is None
    if own:
        con = db.connect(db.db_path(review))
    try:
        page = render(gather(con, review), review)
    finally:
        if own:
            con.close()
    path = out_path(review)
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old != page:
        path.write_text(page, encoding="utf-8")
        return path, True
    return path, False


def main() -> int:
    ap = argparse.ArgumentParser(description="render reviews/<id>/<id>-dashboard.html from the review's database")
    ap.add_argument("review")
    ap.add_argument("--open", action="store_true", help="open the page in the default browser")
    ap.add_argument("--no-sync", action="store_true", help="render from the database as it is")
    a = ap.parse_args()
    review = rv.resolve(a.review)
    if not a.no_sync:
        db.sync(review, quiet=True)
    path, changed = write(review)
    print(f"{path.relative_to(rv.ROOT)} {'(updated)' if changed else '(unchanged)'}")
    if a.open:
        webbrowser.open(path.as_uri())
    return 0


if __name__ == "__main__":
    sys.exit(main())
