r"""dashboard.py — the review dashboard, rendered from the database.

    python scripts/dashboard.py <review> [--open]

Writes reviews/<id>/<id>-dashboard.html — one self-contained page (no
network, no scripts) built entirely from reviews/<id>/<id>.sqlite. It
answers the reviewer's three questions, in this order (redesigned
2026-09-15 at the reviewer's request — the first version "was very
cluttered and didn't tell me what I need to know"):

1. **508 FPC — did we test every view for each modality?** One row per
   functional performance criterion (no-vision, low-vision, …): views
   done / views sampled, check rows answered / blank / failing, and the
   names of the views still owed.
2. **Views — what are we tracking, and is each one complete?** One row per
   sampled view: the page in words, its locator, the sweep and its triage,
   one cell per modality with the latest run's Result, and "done n/8"
   (seven modality cells with a Result + a triaged sweep).
3. **WCAG 2.2 AA — what passes and what fails?** Headline counts
   (passing / failing / n-a / undecided) and, per principle, a table of
   criteria with the 05 outcome, the findings behind it, the check
   evidence, and the vendor's claim.

Then **Next** (pending walkthrough steps, 05 decisions waiting on a
measured fail, tasks without a verdict) and, folded away, the definition
of done, findings, vendor delta, integrity and the state-log history.
Every run, walkthrough and stage file is a relative link, so the page is
the reviewer's map of the review folder.

Regenerated by every `review_db.py sync` (which validate / status /
coverage / log-test / the probe all call), so it is never behind the
files by more than one command. Deterministic — no timestamps; the header
carries the source hash — so a diff on the committed page means the review
changed. Never hand-edit it.

Colour conventions follow the dataviz status palette: every status carries
a glyph and a word as well as a colour, so nothing reads by colour alone.
"""
from __future__ import annotations

import argparse
import html
import pathlib
import re
import sys
import webbrowser

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import review as rv  # noqa: E402
import review_db as db  # noqa: E402

OUTCOME_CLASS = {"Supports": "good", "Partially Supports": "serious", "Does Not Support": "critical",
                 "Not Applicable": "neutral", "Not Evaluated": "empty"}
OUTCOME_GLYPH = {"Supports": "✓", "Partially Supports": "!", "Does Not Support": "✗",
                 "Not Applicable": "–", "Not Evaluated": "·"}
RESULT_CLASS = {"Works": "good", "Works with issues": "warning", "Broken": "critical", "N/A": "neutral",
                "Not set": "pending"}
RESULT_GLYPH = {"Works": "✓", "Works with issues": "!", "Broken": "✗", "N/A": "n", "Not set": "?"}
RESULTED = ("Works", "Works with issues", "Broken", "N/A")
MOD_ABBR = {"no-vision": "NV", "low-vision": "LV", "no-color": "NC", "no-hearing": "NH",
            "no-speech": "NS", "motor": "MO", "cognition": "CO"}
MOD_WORD = {"no-vision": "no vision (screen reader)", "low-vision": "low vision (zoom, contrast)",
            "no-color": "no colour (grayscale)", "no-hearing": "no hearing", "no-speech": "no speech",
            "motor": "motor (keyboard only)", "cognition": "cognition"}
SEV_CLASS = {"Blocker": "critical", "Major": "serious", "Minor": "warning"}
VERDICT_CLASS = {"Pass": "good", "Pass with barriers": "warning", "Fail": "critical"}
VERDICT_GLYPH = {"Pass": "✓", "Pass with barriers": "!", "Fail": "✗"}
SWEEP_CHECKS = ("W1", "W2", "W3")


def e(s) -> str:
    return html.escape("" if s is None else str(s), quote=True)


def plain_locator(loc: str) -> str:
    """The locator without its markdown backticks."""
    return (loc or "").strip().strip("`").strip()


# --------------------------------------------------------------------------
# data — state_data() plus the per-view / per-criterion detail the page needs
# --------------------------------------------------------------------------
def gather(con, review: pathlib.Path) -> dict:
    rid = review.name
    d = db.state_data(con, rid)
    q = lambda sql, **kw: con.execute(sql, {"r": rid, **kw}).fetchall()  # noqa: E731

    # ---- views: one record per sampled view with every cell's latest run ----
    views = []
    d["removed_views"] = [{"view": v, "name": re.sub(r"\s+—\s+proposed \d{4}-\d{2}-\d{2}.*$", "", n or ""), "removed": r}
                          for v, n, r in q("SELECT view_id, name, removed FROM views WHERE review_id=:r AND removed<>'' ORDER BY CASE WHEN view_id LIKE 'S%' THEN 0 ELSE 1 END, CAST(substr(view_id,2) AS INTEGER)")]
    for vid, name, loc, represents, kind in q("""
            SELECT view_id, name, locator, represents, kind FROM views WHERE review_id=:r AND removed=''
            ORDER BY CASE WHEN view_id LIKE 'S%' THEN 0 ELSE 1 END, CAST(substr(view_id,2) AS INTEGER)"""):
        v = {"view": vid, "name": re.sub(r"\s+—\s+proposed \d{4}-\d{2}-\d{2}.*$", "", name or ""),
             "locator": plain_locator(loc), "represents": represents or "", "kind": kind or "", "cells": {}}
        for mod in rv.REQUIRED_MODALITIES:
            row = q("""SELECT run_id, result, tool,
                       (SELECT COUNT(*) FROM check_outcomes ck WHERE ck.review_id=runs.review_id AND ck.run_id=runs.run_id AND ck.outcome=''),
                       (SELECT COUNT(*) FROM check_outcomes ck WHERE ck.review_id=runs.review_id AND ck.run_id=runs.run_id AND ck.outcome IN ('fail','partial'))
                       FROM runs WHERE review_id=:r AND UPPER(view_id)=UPPER(:v) AND modality=:m ORDER BY run_id DESC LIMIT 1""",
                    v=vid, m=mod)
            v["cells"][mod] = ({"run": row[0][0], "result": row[0][1] or "Not set", "tool": row[0][2] or "",
                                "blank": row[0][3], "fails": row[0][4]} if row else None)
        sweeps = q("""SELECT run_id, tool,
                      (SELECT COUNT(*) FROM check_outcomes ck WHERE ck.review_id=runs.review_id AND ck.run_id=runs.run_id
                       AND ck.check_id IN ('W1','W2','W3') AND ck.outcome<>'')
                      FROM runs WHERE review_id=:r AND UPPER(view_id)=UPPER(:v) AND LOWER(tool) IN ('axe','wave') ORDER BY run_id""", v=vid)
        v["sweeps"] = [{"run": s[0], "tool": s[1], "triaged": s[2]} for s in sweeps]
        v["sweep_triaged"] = any(s["triaged"] >= len(SWEEP_CHECKS) for s in v["sweeps"])
        v["cells_done"] = sum(1 for c in v["cells"].values() if c and c["result"] in RESULTED)
        v["done"] = v["cells_done"] + (1 if v["sweep_triaged"] else 0)
        v["done_of"] = len(rv.REQUIRED_MODALITIES) + 1
        v["findings"] = [f for (f,) in q("SELECT finding_id FROM findings WHERE review_id=:r AND withdrawn=0 AND UPPER(view_id)=UPPER(:v) ORDER BY finding_id", v=vid)]
        views.append(v)
    d["views"] = views

    # ---- FPC: per modality, which views are done and which are owed ----
    for f in d["fpc"]:
        mod = f["modality"]
        f["names"] = [f"{code} {name}" for code, name in rv.FPC[mod]]
        f["owed"] = [{"view": v["view"], "name": v["name"],
                      "state": (v["cells"][mod]["result"] if v["cells"][mod] else "not run"),
                      "run": (v["cells"][mod]["run"] if v["cells"][mod] else ""),
                      "blank": (v["cells"][mod]["blank"] if v["cells"][mod] else 0)}
                     for v in views if not (v["cells"][mod] and v["cells"][mod]["result"] in RESULTED)]
        f["done_views"] = [v["view"] for v in views if v["cells"][mod] and v["cells"][mod]["result"] in RESULTED]
        f["broken_views"] = [v["view"] for v in views if v["cells"][mod] and v["cells"][mod]["result"] in ("Broken", "Works with issues")]

    # ---- criteria: outcome, evidence, findings, vendor claim ----
    evidence = {sc: (a, fl) for sc, a, fl in q("""
        SELECT cc.sc, SUM(ck.outcome IN ('pass','fail','partial','n/a')), SUM(ck.outcome IN ('fail','partial'))
        FROM check_outcomes ck JOIN check_criteria cc USING (check_id) WHERE ck.review_id=:r GROUP BY cc.sc""")}
    pending = {sc for (sc,) in q("""
        SELECT DISTINCT cc.sc FROM check_outcomes ck JOIN check_criteria cc USING (check_id)
        JOIN criterion_outcomes co ON co.review_id=ck.review_id AND co.sc=cc.sc
        WHERE ck.review_id=:r AND ck.outcome IN ('fail','partial') AND co.outcome='Not Evaluated'""")}
    findings_by_sc = {}
    for sc, fid in q("""SELECT fc.sc, fc.finding_id FROM finding_criteria fc JOIN findings f USING (review_id, finding_id)
                        WHERE fc.review_id=:r AND f.withdrawn=0 ORDER BY fc.sc, fc.finding_id"""):
        findings_by_sc.setdefault(sc, []).append(fid)
    d["criteria"] = []
    for sc, n, lv, p, pn, o, c, tf, u, rem in q("""
            SELECT w.sc, w.name, w.level, w.principle_no, w.principle, o.outcome, o.vendor_claim, o.task_findings,
                   w.understanding_url, o.remarks FROM wcag_criteria w
            LEFT JOIN criterion_outcomes o ON o.sc=w.sc AND o.review_id=:r
            WHERE w.in_target=1 ORDER BY w.sort_key"""):
        answered, failing = evidence.get(sc, (0, 0))
        claim = next((k for k in ("Partially Supports", "Does Not Support", "Not Applicable", "Not Evaluated", "Supports")
                      if (c or "").startswith(k)), "")
        outcome = o or "Not Evaluated"
        delta = ""
        if claim and outcome != "Not Evaluated" and claim != "Not Evaluated":
            diff = db.CLAIM_RANK.get(outcome, 0) - db.CLAIM_RANK.get(claim, 0)
            delta = "worse" if diff < 0 else "better" if diff > 0 else "same"
        d["criteria"].append({
            "sc": sc, "name": n, "level": lv, "principle_no": str(p), "principle": pn, "outcome": outcome,
            "provisional": "provisional" in (rem or "").lower()[:60],
            "claim": claim, "claim_full": c or "", "delta": delta, "url": u or "",
            "findings": findings_by_sc.get(sc, []), "rollup": tf or "",
            "answered": answered or 0, "failing": failing or 0, "pending": sc in pending})
    crit = d["criteria"]
    d["wcag_summary"] = {
        "passing": sum(1 for c in crit if c["outcome"] == "Supports"),
        "failing": sum(1 for c in crit if c["outcome"] in ("Partially Supports", "Does Not Support")),
        "na": sum(1 for c in crit if c["outcome"] == "Not Applicable"),
        "undecided": sum(1 for c in crit if c["outcome"] == "Not Evaluated"),
        "undecided_pending": sum(1 for c in crit if c["outcome"] == "Not Evaluated" and c["pending"]),
        "undecided_evidenced": sum(1 for c in crit if c["outcome"] == "Not Evaluated" and c["answered"] and not c["pending"]),
        "undecided_blank": sum(1 for c in crit if c["outcome"] == "Not Evaluated" and not c["answered"]),
    }

    # ---- the rest (folded) ----
    d["findings_list"] = [{"id": f, "severity": s or "", "section": sec, "view": v or "", "task": t or "",
                           "where": w or "", "withdrawn": bool(wd), "criteria": [x for x in (c or "").split(",") if x],
                           "runs": sorted(set((r or "").split(",")) - {""})}
                          for f, s, sec, v, t, w, wd, c, r in q("""
        SELECT f.finding_id, f.severity, f.section, f.view_id, f.task_id, f.where_text, f.withdrawn,
               (SELECT group_concat(sc) FROM (SELECT sc FROM finding_criteria fc WHERE fc.review_id=f.review_id AND fc.finding_id=f.finding_id ORDER BY sc)),
               (SELECT group_concat(run_id) FROM (SELECT run_id FROM finding_runs fr WHERE fr.review_id=f.review_id AND fr.finding_id=f.finding_id ORDER BY run_id))
        FROM findings f WHERE f.review_id=:r
        ORDER BY f.withdrawn, CASE WHEN f.severity LIKE 'Blocker%' THEN 0 WHEN f.severity LIKE 'Major%' THEN 1 WHEN f.severity LIKE 'Minor%' THEN 2 ELSE 3 END, f.finding_id""")]
    d["measured_detail"] = [{"sc": sc, "name": n, "check": c, "runs": (runs or "").split(",")}
                            for sc, n, c, runs in q("""
        SELECT cc.sc, w.name, ck.check_id, group_concat(ck.run_id)
        FROM check_outcomes ck JOIN check_criteria cc USING (check_id)
        JOIN criterion_outcomes co ON co.review_id=ck.review_id AND co.sc=cc.sc
        JOIN wcag_criteria w ON w.sc=cc.sc
        WHERE ck.review_id=:r AND ck.outcome IN ('fail','partial') AND co.outcome='Not Evaluated'
        GROUP BY cc.sc, ck.check_id ORDER BY cc.sc, ck.check_id""")]
    d["tasks_detail"] = [{"task": t, "name": n, "verdict": v}
                         for t, n, v in q("SELECT task_id, name, verdict FROM tasks WHERE review_id=:r ORDER BY task_id")]
    d["integrity_detail"] = db.integrity(con, rid)
    d["unanswered_runs"] = [{"run": r, "view": v, "modality": m, "tool": t, "blank": n} for r, v, m, t, n in q("""
        SELECT r.run_id, r.view_id, r.modality, r.tool, COUNT(*) FROM runs r JOIN check_outcomes ck USING (review_id, run_id)
        JOIN views v ON v.review_id=r.review_id AND UPPER(v.view_id)=UPPER(r.view_id)
        WHERE r.review_id=:r AND ck.outcome='' AND v.removed='' GROUP BY r.run_id ORDER BY COUNT(*) DESC, r.run_id""")]
    log = review / "state-log.md"
    d["history"] = []
    if log.exists():
        for ln in log.read_text(encoding="utf-8").splitlines():
            if ln.startswith("| 20"):
                d["history"].append([c.strip() for c in ln.strip().strip("|").split("|")])
    return d


# --------------------------------------------------------------------------
# render
# --------------------------------------------------------------------------
CSS = """
:root{color-scheme:light;--bg:#f6f6f4;--surface:#fcfcfb;--line:#dcdbd6;--ink:#0b0b0b;--ink2:#52514e;--ink3:#7d7c78;
--track:#e8e7e3;--fill:#2a78d6;--good:#0ca30c;--warning:#c98a00;--serious:#ec835a;--critical:#d03b3b;--neutral:#9a9994;
--good-bg:#e4f5e4;--warning-bg:#fff3d6;--serious-bg:#fde6dc;--critical-bg:#f9dcdc;--neutral-bg:#ecebe8;--pending-bg:#e6effa;--link:#1d5fb0}
@media (prefers-color-scheme: dark){:root{color-scheme:dark;--bg:#121211;--surface:#1a1a19;--line:#33332f;--ink:#fff;--ink2:#c3c2b7;--ink3:#8f8e87;
--track:#2a2a27;--fill:#3987e5;--warning:#fab219;--good-bg:#173d17;--warning-bg:#4a3a0e;--serious-bg:#4d2a1c;--critical-bg:#4d1f1f;--neutral-bg:#2c2c29;--pending-bg:#1c2c40;--link:#7db3f0}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.45 system-ui,Segoe UI,Roboto,sans-serif;padding:16px}
main{max-width:1400px;margin:0 auto}a{color:var(--link)}h1{font-size:22px;margin:0 0 4px}
h2{font-size:16px;margin:0 0 4px}h2 small{font-weight:400;color:var(--ink2);font-size:13px;margin-left:8px}
h3{font-size:13px;margin:16px 0 6px;color:var(--ink2)}.sub{color:var(--ink2);margin:0 0 12px}.sub code{font-size:12px}
.lede{color:var(--ink2);margin:0 0 10px;font-size:13px}
section{background:var(--surface);border:1px solid var(--line);border-radius:8px;padding:14px 16px;margin:0 0 16px;min-width:0}
table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;padding:5px 8px;border-bottom:1px solid var(--line);vertical-align:top}
th{color:var(--ink2);font-weight:600;white-space:nowrap}td.num,th.num{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}.scroll{overflow-x:auto}
tr.complete td{color:var(--ink2)}
.chips{display:flex;flex-wrap:wrap;gap:6px;margin:6px 0}.chip{display:inline-flex;align-items:center;gap:5px;padding:2px 9px;border-radius:999px;border:1px solid var(--line);background:var(--neutral-bg);font-size:12px;white-space:nowrap;color:var(--ink)}
.chip.good{background:var(--good-bg);border-color:var(--good)}.chip.warning{background:var(--warning-bg);border-color:var(--warning)}
.chip.serious{background:var(--serious-bg);border-color:var(--serious)}.chip.critical{background:var(--critical-bg);border-color:var(--critical)}
.chip.pending{background:var(--pending-bg);border-color:var(--fill)}.chip.empty{background:transparent;border-style:dashed;color:var(--ink2)}
a.chip{text-decoration:none}
.heroes{display:flex;flex-wrap:wrap;gap:8px 28px;margin:4px 0 12px}.hero{font-size:30px;font-weight:700;line-height:1.05}.hero small{display:block;font-size:12px;font-weight:400;color:var(--ink2);margin-top:2px}
.hero.good{color:var(--good)}.hero.critical{color:var(--critical)}.hero.serious{color:var(--serious)}.hero.pending{color:var(--fill)}.hero.neutral{color:var(--ink2)}
.bar{display:inline-block;width:120px;height:9px;background:var(--track);border-radius:4px;overflow:hidden;vertical-align:middle;margin-right:8px}.bar i{display:block;height:100%;background:var(--fill);border-radius:4px}
.bar.ok i{background:var(--good)}
.mx td{padding:4px 5px;text-align:center;white-space:nowrap}.mx td.v,.mx th.v{text-align:left}.mx td.v{min-width:220px;max-width:340px}
.mx a.c,.mx span.c{display:inline-block;min-width:30px;padding:2px 5px;border-radius:4px;border:1px solid var(--line);text-decoration:none;color:var(--ink);font-size:12px;line-height:1.3;font-weight:600}
.mx .c.good{background:var(--good-bg);border-color:var(--good)}.mx .c.warning{background:var(--warning-bg);border-color:var(--warning)}
.mx .c.critical{background:var(--critical-bg);border-color:var(--critical)}.mx .c.neutral{background:var(--neutral-bg);font-weight:400}.mx .c.pending{background:var(--pending-bg);border-color:var(--fill)}
.mx span.c.none{border-style:dashed;color:var(--ink3);font-weight:400;background:transparent}
.legend{display:flex;flex-wrap:wrap;gap:6px 14px;font-size:12px;color:var(--ink2);margin:6px 0 10px}
.legend span::before{content:"";display:inline-block;width:11px;height:11px;border-radius:3px;border:1px solid var(--line);margin-right:5px;vertical-align:-1px}
.legend .good::before{background:var(--good-bg);border-color:var(--good)}.legend .serious::before{background:var(--serious-bg);border-color:var(--serious)}
.legend .critical::before{background:var(--critical-bg);border-color:var(--critical)}.legend .neutral::before{background:var(--neutral-bg)}
.legend .warning::before{background:var(--warning-bg);border-color:var(--warning)}.legend .pending::before{background:var(--pending-bg);border-color:var(--fill)}
.legend .empty::before{border-style:dashed}
ul{margin:4px 0 8px 18px;padding:0}li{margin:3px 0}.muted{color:var(--ink3)}.small{font-size:12px}.key{font-weight:700;color:var(--serious)}
details{margin:0 0 10px}summary{cursor:pointer;font-weight:600;color:var(--ink2);padding:6px 0}details[open] summary{margin-bottom:6px}
.done{display:grid;grid-template-columns:minmax(150px,auto) 1fr auto;gap:4px 12px;align-items:center;font-variant-numeric:tabular-nums;max-width:640px}
.done .name{white-space:nowrap}.done .name.ok::before{content:"✓ ";color:var(--good)}.done .name.no::before{content:"✗ ";color:var(--ink3)}
.done .bar{width:auto;display:block}.done .n{color:var(--ink2);font-size:12px;white-space:nowrap}
.sc{font-weight:700;white-space:nowrap}.lvl{color:var(--ink3);font-size:11px;margin-left:4px}
td.name{min-width:180px}td.ev{font-size:12px;color:var(--ink2);white-space:nowrap}td.claim{font-size:12px;white-space:nowrap}
.delta.worse{color:var(--critical);font-weight:600}.delta.better{color:var(--good);font-weight:600}.delta.same{color:var(--ink3)}
.owed{font-size:12px;color:var(--ink2)}.owed a{color:var(--link);text-decoration:none}.owed a.pending{font-weight:600}
"""


def chip(text, cls="", glyph="", title="") -> str:
    t = f" title='{e(title)}'" if title else ""
    return f'<span class="chip {cls}"{t}>{e(glyph)}{" " if glyph else ""}{e(text)}</span>'


def bar(done: int, total: int) -> str:
    pct = 100 * done / total if total else 0
    return f"<span class='bar {'ok' if total and done >= total else ''}'><i style='width:{pct:.0f}%'></i></span>"


def run_link(run: str, text: str = "", cls: str = "", title: str = "") -> str:
    return f"<a class='{cls}' href='evidence/runs/{e(run)}/run.md' title='{e(title)}'>{e(text or run)}</a>"


def render(d: dict, review: pathlib.Path) -> str:
    L = []
    sat = sum(1 for r in d["completion"] if r["total"] and r["done"] >= r["total"])
    n_views = len(d["views"])
    L.append(f"<title>{e(d['product'])} review dashboard</title><style>{CSS}</style><main>")
    L.append(f"<h1>{e(d['product'])} <span class='muted'>· {e(d['review'])}</span></h1>")
    L.append(f"<p class='sub'>decision <b>{e(d['decision'])}</b> · report <b>{e(d['report_status'] or '—')}</b> · "
             f"definition of done <b>{sat}/{len(d['completion'])}</b> (<a href='#done'>detail</a>) · "
             f"{d['runs']} runs · {d['findings_live']} live findings · source <code>{e(d['source_sha'][:12])}</code> · "
             f"generated by <code>scripts/dashboard.py</code> — never hand-edited</p>")
    L.append("<div class='chips'>" + "".join(
        chip(f"{t['task']} {t['verdict']}", VERDICT_CLASS.get(t["verdict"], "empty"), VERDICT_GLYPH.get(t["verdict"], "·"),
             title=t["name"]) for t in d["tasks_detail"]) + " <a class='small' href='04-task-testing.md'>task walks, 04 §A</a></div>")

    # ---------------------------------------------------------------- 1. FPC
    fpc_done = sum(1 for f in d["fpc"] if f["views_resulted"] >= f["views"])
    L.append(f"<section id='fpc'><h2>1 · 508 functional performance criteria <small>{fpc_done} of {len(d['fpc'])} modalities tested on every view</small></h2>")
    L.append("<p class='lede'>A view counts as tested for a modality when its latest run under that modality has a Result "
             "(Works / Works with issues / Broken / N/A). Blank rows are check rows still unanswered in logged runs.</p>")
    L.append("<div class='scroll'><table><tr><th>508 FPC</th><th>modality</th><th>views tested</th><th class='num'>answered</th>"
             "<th class='num'>blank</th><th class='num'>failing rows</th><th>still owed</th></tr>")
    for f in d["fpc"]:
        complete = f["views_resulted"] >= f["views"]
        owed = f["owed"]
        if not owed:
            owed_html = "<span class='chip good'>✓ every view</span>"
        elif len(owed) == n_views:
            owed_html = "<span class='owed'>every view — " + ", ".join(
                run_link(o["run"], f"{o['view']} ({o['blank']} blank)", "pending", f"{o['name']} — {o['run']} logged, no Result")
                if o["run"] else f"<span title='{e(o['name'])}'>{e(o['view'])}</span>" for o in owed) + "</span>"
        else:
            owed_html = "<span class='owed'>" + ", ".join(
                run_link(o["run"], f"{o['view']} ({o['blank']} blank)", "pending", f"{o['name']} — {o['run']} logged, no Result")
                if o["run"] else f"<span title='{e(o['name'])}'>{e(o['view'])} (not run)</span>" for o in owed) + "</span>"
        L.append(f"<tr class='{'complete' if complete else ''}'><td>{'<br>'.join(e(n) for n in f['names'])}</td>"
                 f"<td>{e(MOD_WORD.get(f['modality'], f['modality']))}</td>"
                 f"<td>{bar(f['views_resulted'], f['views'])}<span class='small'>{f['views_resulted']}/{f['views']}</span></td>"
                 f"<td class='num'>{f['answered']}</td><td class='num'>{f['blank']}</td>"
                 f"<td class='num'>{f['fails'] or ''}</td><td>{owed_html}</td></tr>")
    L.append("</table></div></section>")

    # ------------------------------------------------------------- 2. views
    views_done = sum(1 for v in d["views"] if v["done"] >= v["done_of"])
    L.append(f"<section id='views'><h2>2 · Views under review <small>{views_done} of {n_views} complete</small></h2>")
    L.append("<p class='lede'>One row per sampled view (03 §3.1). A view is complete when all seven modality cells have a Result and its "
             "automated sweep is triaged (W1–W3 answered). Each cell links to the latest run for that view and modality.</p>")
    L.append("<div class='legend'><span class='good'>✓ Works</span><span class='warning'>! Works with issues</span><span class='critical'>✗ Broken</span>"
             "<span class='neutral'>n N/A</span><span class='pending'>? logged, no Result (blank rows)</span><span class='empty'>· not run</span></div>")
    L.append("<div class='scroll'><table class='mx'><tr><th class='v'>view</th><th>sweep</th>" + "".join(
        f"<th title='{e(MOD_WORD.get(m, m))}'>{MOD_ABBR[m]}</th>" for m in rv.REQUIRED_MODALITIES) + "<th>done</th><th class='v'>findings</th></tr>")
    for v in d["views"]:
        loc = v["locator"]
        href = loc if loc.startswith("http") else ""
        name_html = (f"<a href='{e(href)}'>{e(v['name'])}</a>" if href else e(v["name"]))
        kind = f" <span class='muted small'>random</span>" if v["kind"] == "random" else ""
        L.append(f"<tr><td class='v' title='{e(loc)}'><b>{e(v['view'])}</b> {name_html}{kind}</td>")
        if v["sweeps"]:
            L.append("<td>" + " ".join(
                run_link(s["run"], f"{s['tool']} {s['triaged']}/{len(SWEEP_CHECKS)}", "c " + ("good" if s["triaged"] >= len(SWEEP_CHECKS) else "pending"),
                         f"{s['run']} — {s['tool']} sweep, triage rows answered {s['triaged']} of {len(SWEEP_CHECKS)}") for s in v["sweeps"]) + "</td>")
        else:
            L.append("<td><span class='c none'>·</span></td>")
        for mod in rv.REQUIRED_MODALITIES:
            c = v["cells"][mod]
            if not c:
                L.append(f"<td><span class='c none' title='{e(v['view'])} × {e(mod)} — not run'>·</span></td>")
                continue
            cls = RESULT_CLASS.get(c["result"], "pending")
            label = RESULT_GLYPH.get(c["result"], "?") + (f" {c['blank']}" if c["result"] == "Not set" and c["blank"] else "")
            title = f"{c['run']} — {v['view']} × {mod} ({c['tool']}) — {c['result']}" + \
                (f"; {c['blank']} blank row(s)" if c["blank"] else "") + (f"; {c['fails']} failing row(s)" if c["fails"] else "")
            L.append(f"<td>{run_link(c['run'], label, 'c ' + cls, title)}</td>")
        L.append(f"<td class='num'>{'<b>' if v['done'] >= v['done_of'] else ''}{v['done']}/{v['done_of']}{'</b>' if v['done'] >= v['done_of'] else ''}</td>")
        L.append("<td class='v small'>" + (", ".join(f"<a href='04-task-testing.md'>{e(f)}</a>" for f in v["findings"]) or "<span class='muted'>—</span>") + "</td></tr>")
    L.append("</table></div>")
    if d["removed_views"]:
        L.append("<p class='small muted'>Removed from the sample, kept on record (runs and findings stay): " + "; ".join(
            f"<b>{e(r['view'])}</b> {e(r['name'])} ({e(r['removed'])})" for r in d["removed_views"]) + "</p>")
    L.append("</section>")

    # ------------------------------------------------------------ 3. WCAG
    s = d["wcag_summary"]
    L.append(f"<section id='wcag'><h2>3 · WCAG 2.2 AA — 55 criteria <small>{s['passing'] + s['failing'] + s['na']} decided</small></h2>")
    L.append("<p class='lede'>The 05 outcome per criterion. Failing = Partially Supports or Does Not Support. "
             "Evidence is the count of answered check rows mapped to the criterion across all runs; a criterion with a failing check row and no 05 outcome is waiting on the reviewer's decision.</p>")
    L.append("<div class='heroes'>"
             f"<div class='hero good'>{s['passing']}<small>✓ passing (Supports)</small></div>"
             f"<div class='hero critical'>{s['failing']}<small>✗ failing (Partially / Does Not Support)</small></div>"
             f"<div class='hero neutral'>{s['na']}<small>– not applicable</small></div>"
             f"<div class='hero pending'>{s['undecided']}<small>· undecided — {s['undecided_pending']} waiting on a decision, {s['undecided_evidenced']} with evidence, {s['undecided_blank']} untested</small></div>"
             "</div>")
    for pno, pname in sorted(rv.PRINCIPLES.items()):
        cs = [c for c in d["criteria"] if c["principle_no"] == pno]
        dec = sum(1 for c in cs if c["outcome"] != "Not Evaluated")
        fail = sum(1 for c in cs if c["outcome"] in ("Partially Supports", "Does Not Support"))
        L.append(f"<h3>{e(pno)} {e(pname)} <span class='muted'>— {dec}/{len(cs)} decided, {fail} failing</span></h3>")
        L.append("<div class='scroll'><table><tr><th>criterion</th><th>outcome</th><th>findings</th><th>evidence</th><th>vendor claim</th></tr>")
        for c in cs:
            oc = c["outcome"]
            ocls = OUTCOME_CLASS.get(oc, "empty")
            if oc == "Not Evaluated":
                if c["pending"]:
                    otext, ocls, glyph = "decision needed", "pending", "?"
                elif c["answered"]:
                    otext, glyph = "undecided", "·"
                else:
                    otext, glyph = "untested", "·"
            else:
                otext, glyph = oc, OUTCOME_GLYPH.get(oc, "·")
            if c["provisional"]:
                otext += " (provisional)"
            ev = (f"{c['answered']} answered" + (f", {c['failing']} failing" if c["failing"] else "")) if c["answered"] else "—"
            claim = e(c["claim"]) if c["claim"] else "<span class='muted'>—</span>"
            if c["delta"]:
                claim += f" <span class='delta {c['delta']}' title='{e(c['claim_full'][:120])}'>{e(c['delta'])}</span>"
            fl = ", ".join(f"<a href='04-task-testing.md'>{e(f)}</a>" for f in c["findings"]) or "<span class='muted'>—</span>"
            L.append(f"<tr><td class='name'><span class='sc'>{e(c['sc'])}</span> <a href='{e(c['url'])}' class='muted'>{e(c['name'])}</a>"
                     f"<span class='lvl'>{e(c['level'])}</span></td>"
                     f"<td><a class='chip {ocls}' href='05-results.md'>{e(glyph)} {e(otext)}</a></td>"
                     f"<td class='small'>{fl}</td><td class='ev'>{e(ev)}</td><td class='claim'>{claim}</td></tr>")
        L.append("</table></div>")
    L.append("</section>")

    # ------------------------------------------------------------- 4. next
    wt = d["walkthrough_pending"]
    L.append("<section id='next'><h2>4 · Next</h2>")
    if wt:
        files = sorted({x["file"] for x in wt})
        L.append(f"<h3>Walkthrough — {len(wt)} of {d['walkthrough_total']} steps pending</h3><ul>")
        for x in wt:
            L.append(f"<li><a href='{e(x['file'])}'>{e(x['step'])}</a>{' <span class=key>KEY</span>' if x['key'] else ''} — {e(x['title'])}</li>")
        L.append("</ul>" + "".join(f"<p class='small muted'>file: <a href='{e(f)}'>{e(f)}</a></p>" for f in files))
    if d["measured_detail"]:
        L.append(f"<h3>05 decisions waiting on a failing check ({len(d['measured_detail'])})</h3><ul>")
        for m in d["measured_detail"]:
            L.append(f"<li><b>{e(m['sc'])}</b> {e(m['name'])} — {e(m['check'])} on " + ", ".join(run_link(r) for r in m["runs"]) + "</li>")
        L.append("</ul>")
    not_run = [t for t in d["tasks_detail"] if t["verdict"] not in VERDICT_CLASS]
    if not_run:
        L.append("<h3>Task walks without a verdict</h3><ul>" + "".join(
            f"<li><b>{e(t['task'])}</b> {e(t['name'])} <span class='muted'>({e(t['verdict'])})</span></li>" for t in not_run)
                 + "</ul><p class='small'><a href='04-task-testing.md'>04-task-testing.md</a> §A</p>")
    if not (wt or d["measured_detail"] or not_run):
        L.append("<p>Nothing pending — run <code>review.py validate</code> for the definition of done.</p>")
    L.append("</section>")

    # ---------------------------------------------------------- folded detail
    L.append("<section id='detail'><h2>Detail</h2>")
    # definition of done
    L.append(f"<details id='done'><summary>Definition of done — {sat}/{len(d['completion'])} predicates</summary><div class='done'>")
    for r in d["completion"]:
        ok = r["total"] and r["done"] >= r["total"]
        pct = 100 * r["done"] / r["total"] if r["total"] else 0
        L.append(f"<span class='name {'ok' if ok else 'no'}' title='{e(r['description'])}'>{e(r['name'])}</span>"
                 f"<span class='bar {'ok' if ok else ''}'><i style='width:{pct:.0f}%'></i></span>"
                 f"<span class='n'>{r['done']}/{r['total']}</span>")
    L.append("</div><p class='small muted'>C12 is the reviewer's act alone. Source: <code>review_db.py completion</code>.</p></details>")
    # findings
    sv = d["severity"]
    L.append(f"<details><summary>Findings — Blocker {sv['Blocker']} · Major {sv['Major']} · Minor {sv['Minor']}"
             + (f" · unrated {sv['unrated']}" if sv["unrated"] else "") + f" · withdrawn {d['findings_withdrawn']}</summary>")
    L.append("<div class='scroll'><table><tr><th>ID</th><th>severity</th><th>where</th><th>criteria</th><th>runs</th></tr>")
    for f in d["findings_list"]:
        sev = re.search(r"Blocker|Major|Minor", f["severity"] or "")
        cls = SEV_CLASS.get(sev.group(0), "") if sev else ""
        style = " style='opacity:.55'" if f["withdrawn"] else ""
        L.append(f"<tr{style}><td><a href='04-task-testing.md'>{e(f['id'])}</a></td><td>{chip(f['severity'][:60] or '—', cls) if not f['withdrawn'] else chip('withdrawn')}</td>"
                 f"<td class='small'>{e(f['where'][:140])}</td><td>{e(', '.join(f['criteria']))}</td>"
                 f"<td>{' '.join(run_link(r) for r in f['runs'])}</td></tr>")
    L.append("</table></div></details>")
    # vendor
    v = d["vendor"]
    L.append(f"<details><summary>Vendor claim vs verified — {v['decided']} decided: {v['worse']} worse than claimed, {v['better']} better, {v['same']} as claimed</summary>")
    worse = [c for c in d["criteria"] if c["delta"] == "worse"]
    if worse:
        L.append("<div class='scroll'><table><tr><th>criterion</th><th>vendor claim</th><th>verified</th></tr>")
        for c in worse:
            L.append(f"<tr><td><span class='sc'>{e(c['sc'])}</span> {e(c['name'])}</td><td class='small'>{e(c['claim_full'][:90])}</td><td>{e(c['outcome'])}</td></tr>")
        L.append("</table></div>")
    else:
        L.append("<p class='muted'>no criterion verified worse than claimed</p>")
    L.append("</details>")
    # integrity
    L.append(f"<details><summary>Integrity (C11) — {'clean' if not d['integrity_detail'] else str(len(d['integrity_detail'])) + ' issue type(s)'}</summary>")
    if d["integrity_detail"]:
        L.append("<ul>")
        for i in d["integrity_detail"]:
            items = i["items"]
            L.append(f"<li><b>{e(i['check'])}</b> ({i['count']}) <span class='muted'>— {e(i['description'])}</span><br><span class='small'>"
                     + e("; ".join(str(x) for x in items[:8])) + (f" … +{len(items) - 8}" if len(items) > 8 else "") + "</span></li>")
        L.append("</ul>")
    else:
        L.append("<p>clean</p>")
    L.append("</details>")
    # blank runs
    L.append(f"<details><summary>Runs with blank check rows — {len(d['unanswered_runs'])}</summary><p class='small'>" + ", ".join(
        run_link(u["run"], f"{u['run']} ({u['blank']})", "", f"{u['view']} × {u['modality']} ({u['tool']})") for u in d["unanswered_runs"]) + "</p></details>")
    # history
    L.append("<details><summary>History — state-log.md</summary>")
    if d["history"]:
        cols = ["date", "done", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11", "C12", "runs", "findings", "integrity"]
        L.append("<div class='scroll'><table><tr>" + "".join(f"<th>{c}</th>" for c in cols) + "</tr>")
        for row in d["history"]:
            L.append("<tr>" + "".join(f"<td class='small'>{e(c)}</td>" for c in row) + "</tr>")
        L.append("</table></div>")
    else:
        L.append("<p class='muted'>no rows yet — <code>review_db.py state --log</code></p>")
    L.append("</details>")
    L.append("<p class='small muted'>Stage files: " + " · ".join(f"<a href='{e(x)}'>{e(x)}</a>" for x in rv.STAGES) + "</p></section>")
    L.append("</main>")
    return "<!doctype html><html lang='en'><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>" + "\n".join(L) + "\n"


def out_path(review: pathlib.Path) -> pathlib.Path:
    return review / f"{review.name}-dashboard.html"


def write(review: pathlib.Path, con=None) -> tuple[pathlib.Path, bool]:
    """Render the dashboard from the review's database. Returns (path, changed).
    Byte-stable: an unchanged page is not rewritten."""
    own = con is None
    if own:
        con = db.connect(db.db_path(review))
    try:
        page = render(gather(con, review), review)
    finally:
        if own:
            con.close()
    path = out_path(review)
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old != page:
        path.write_text(page, encoding="utf-8")
        return path, True
    return path, False


def main() -> int:
    ap = argparse.ArgumentParser(description="render reviews/<id>/<id>-dashboard.html from the review's database")
    ap.add_argument("review")
    ap.add_argument("--open", action="store_true", help="open the page in the default browser")
    ap.add_argument("--no-sync", action="store_true", help="render from the database as it is")
    a = ap.parse_args()
    review = rv.resolve(a.review)
    if not a.no_sync:
        db.sync(review, quiet=True)
    path, changed = write(review)
    print(f"{path.relative_to(rv.ROOT)} {'(updated)' if changed else '(unchanged)'}")
    if a.open:
        webbrowser.open(path.as_uri())
    return 0


if __name__ == "__main__":
    sys.exit(main())
